---
version: '2'

  services:
    mongodb:
      image: mongo

    app:
      build: .
      ports:
        - "18888:8888"
      depends_on:
        - mongodb
      links:
        - mongodb
      environment:
        - MONGODB_NAME=development