---
- quote: "I call investing the greatest business in the world … because you never have to swing. You stand at the plate, the pitcher throws you General Motors at 47! U.S. Steel at 39! and nobody calls a strike on you. There's no penalty except opportunity lost. All day you wait for the pitch you like; then when the fielders are asleep, you step up and hit it."
  attribution: Warren Buffet
- quote: "You only have to do a very few things right in your life so long as you don't do too many things wrong."
  attribution: Warren Buffet

- quote: "Should you find yourself in a chronically leaking boat, energy devoted to changing vessels is likely to be a more productive than energy devoted to patching leaks."
  attribution: Warren Buffet
  
- quote: "It is not necessary to do extraordinary things to get extraordinary results."
  attribution: Warren Buffet
  
- quote: "What we learn from history is that people don't learn from history."
  attribution: Warren Buffet
  
- quote: "Chains of habit are too light to be felt until they are too heavy to be broken."
  attribution: Warren Buffet
  
- quote: "There seems to be some perverse human characteristic that likes to make easy things difficult."
  attribution: Warren Buffet
  
- quote: "Nothing sedates rationality like large doses of effortless money."
  attribution: Warren Buffet
  
- quote: "It takes 20 years to build a reputation and five minutes to ruin it. If you think about that, you'll do things differently."
  attribution: Warren Buffet
  
- quote: "It's better to hang out with people better than you. Pick out associates whose behavior is better than yours and you'll drift in that direction."
  attribution: Warren Buffet
  
- quote: "Long ago, Ben Graham taught me that 'Price is what you pay; value is what you get.' Whether we're talking about socks or stocks, I like buying quality merchandise when it is marked down."
  attribution: Warren Buffet
  
- quote: "The most important quality for an investor is temperament, not intellect. You need a temperament that neither derives great pleasure from being with the crowd or against the crowd."
  attribution: Warren Buffet
  
- quote: "Successful Investing takes time, discipline and patience. No matter how great the talent or effort, some things just take time: You can't produce a baby in one month by getting nine women pregnant."
  attribution: Warren Buffet
  
- quote: "I don't look to jump over seven-foot bars; I look around for one-foot bars that I can step over."
  attribution: Warren Buffet
  
- quote: "In the short term, the market is a popularity contest. In the long term, the market is a weighing machine."
  attribution: Warren Buffet
  
- quote: "Opportunities come infrequently. When it rains gold, put out the bucket, not the thimble"
  attribution: Warren Buffet
  
- quote: "Diversification is a protection against ignorance. It makes very little sense for those who know what they're doing."
  attribution: Warren Buffet
  
- quote: "If you aren't willing to own a stock for ten years, don't even think about owning it for ten minutes. Put together a portfolio of companies whose aggregate earnings march upward over the years, and so also will the portfolio's market value."
  attribution: Warren Buffet
  
- quote: "The key to investing is not assessing how much an industry is going to affect society, or how much it will grow, but rather determining the competitive advantage of any given company and, above all, the durability of that advantage."
  attribution: Warren Buffet
  
- quote: "I am a better investor because I am a businessman, and a better businessman because I am an investor."
  attribution: Warren Buffet
  
- quote: "It's far better to buy a wonderful company at a fair price than a fair company at a wonderful price."
  attribution: Warren Buffet
  
- quote: "I will tell you how to become rich. Close the doors. Be fearful when others are greedy. Be greedy when others are fearful."
  attribution: Warren Buffet
  
- quote: "I tell college students, when you get to be my age you will be successful if the people who you hope to have love you, do love you."
  attribution: Warren Buffet
  
- quote: "The difference between successful people and really successful people is that really successful people say no to almost everything."
  attribution: Warren Buffet
  
- quote: "I've seen more people fail because of liquor and leverage -- leverage being borrowed money. You really don't need leverage in this world much. If you're smart, you're going to make a lot of money without borrowing."
  attribution: Warren Buffet

- quote: "What an investor needs is the ability to correctly evaluate selected businesses. Note that word 'selected': You don't have to be an expert on every company, or even many. You only have to be able to evaluate companies within your circle of competence. The size of that circle is not very important; knowing its boundaries, however, is vital."
  attribution: Warren Buffet